name: CI

on:
  pull_request:
    {}
  release:
    types: [ published ]

env:
  AWS_REGION:     us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  test-aws-cdk-synth:
    environment: test
    name: "[test] AWS CDK synth"
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup runtime
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache NPM
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-build-${{ env.cache-name }}-
            npm-build-
      - name: Install dependencies
        run: |
          npm ci
      - name: Build the CDK app
        run: |
          npm run build
      - name: Run AWS CDK synth
        run: |
          make aws-cdk-synth ARGS="--logs -v --ci --all" AWS_ENVIRONMENT=test
